// Auto-generated by LibreLane
module serdes_8bit(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input[7:0] data_8bit_in,
  input data_en,
  output[7:0] data_8bit_out,
  output bus_free_flag
);
endmodule
